  CREATE TABLE "A01_ALIGNMENT" 
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ALIGNMENT" VARCHAR2(50) NOT NULL ENABLE, 
	 CONSTRAINT "A01_ALIGNMENT_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "A01_CONTRIBUTORY_CAUSE" 
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"CONTRIBUTORY_CAUSE" VARCHAR2(100) NOT NULL ENABLE, 
	"CAUSE_GROUP" VARCHAR2(100) DEFAULT 'UNKNOWN' NOT NULL ENABLE, 
	 CONSTRAINT "A01_CONTRIBUTORY_CAUSE_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "A01_CRASH_TYPE" 
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"CRASH_TYPE" VARCHAR2(50) NOT NULL ENABLE, 
	 CONSTRAINT "A01_CRASH_TYPE_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "A01_DAMAGE" 
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"DAMAGE" VARCHAR2(50) NOT NULL ENABLE, 
	"DAMAGE_LOW" NUMBER, 
	"DAMAGE_HIGH" NUMBER, 
	 CONSTRAINT "A01_DAMAGE_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "A01_DEVICE_CONDITION" 
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"DEVICE_CONDITION" VARCHAR2(50) NOT NULL ENABLE, 
	 CONSTRAINT "A01_DEVICE_CONDITION_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "A01_FIRST_CRASH_TYPE" 
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"FIRST_CRASH_TYPE" VARCHAR2(50) NOT NULL ENABLE, 
	 CONSTRAINT "A01_FIRST_CRASH_TYPE_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "A01_LIGHTING_CONDITION" 
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"LIGHTING_CONDITION" VARCHAR2(50) NOT NULL ENABLE, 
	 CONSTRAINT "A01_LIGHTING_CONDITION_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "A01_MOST_SEVERE_INJURY" 
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"MOST_SEVERE_INJURY" VARCHAR2(50) NOT NULL ENABLE, 
	 CONSTRAINT "A01_MOST_SEVERE_INJURY_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "A01_REPORT_TYPE" 
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"REPORT_TYPE" VARCHAR2(50) NOT NULL ENABLE, 
	 CONSTRAINT "A01_REPORT_TYPE_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "A01_ROADWAY_SURFACE_COND" 
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ROADWAY_SURFACE_COND" VARCHAR2(50) NOT NULL ENABLE, 
	 CONSTRAINT "A01_ROADWAY_SURFACE_COND_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "A01_ROAD_DEFECT" 
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ROAD_DEFECT" VARCHAR2(50) NOT NULL ENABLE, 
	 CONSTRAINT "A01_ROAD_DEFECT_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "A01_STREET_DIRECTION" 
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"STREET_DIRECTION" VARCHAR2(1) NOT NULL ENABLE, 
	"STREET_DIRECTION_DESC" VARCHAR2(5), 
	 CONSTRAINT "A01_STREET_DIRECTION_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "A01_STREET_NAME" 
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"STREET_NAME" VARCHAR2(50) NOT NULL ENABLE, 
	 CONSTRAINT "A01_STREET_NAME_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "A01_TRAFFICWAY_TYPE" 
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"TRAFFICWAY_TYPE" VARCHAR2(50) NOT NULL ENABLE, 
	 CONSTRAINT "A01_TRAFFICWAY_TYPE_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "A01_TRAFFIC_ACCIDENTS" 
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"CRASH_RECORD_ID" VARCHAR2(255), 
	"CRASH_DATE_EST_I" VARCHAR2(1), 
	"CRASH_DATE" DATE, 
	"POSTED_SPEED_LIMIT" NUMBER, 
	"LANE_CNT" NUMBER, 
	"INTERSECTION_RELATED_I" VARCHAR2(1), 
	"NOT_RIGHT_OF_WAY_I" VARCHAR2(1), 
	"HIT_AND_RUN_I" VARCHAR2(1), 
	"DATE_POLICE_NOTIFIED" DATE, 
	"STREET_NO" NUMBER, 
	"BEAT_OF_OCCURRENCE" NUMBER, 
	"PHOTOS_TAKEN_I" VARCHAR2(1), 
	"STATEMENTS_TAKEN_I" VARCHAR2(1), 
	"DOORING_I" VARCHAR2(1), 
	"WORK_ZONE_I" VARCHAR2(1), 
	"WORKERS_PRESENT_I" VARCHAR2(1), 
	"NUM_UNITS" NUMBER, 
	"INJURIES_TOTAL" NUMBER, 
	"INJURIES_FATAL" NUMBER, 
	"INJURIES_INCAPACITATING" NUMBER, 
	"INJURIES_NON_INCAPACITATING" NUMBER, 
	"INJURIES_REPORTED_NOT_EVIDENT" NUMBER, 
	"INJURIES_NO_INDICATION" NUMBER, 
	"INJURIES_UNKNOWN" NUMBER, 
	"CRASH_HOUR" NUMBER, 
	"CRASH_DAY_OF_WEEK" NUMBER, 
	"CRASH_MONTH" NUMBER, 
	"TRAFFIC_CONTROL_DEVICE_ID" NUMBER, 
	"DEVICE_CONDITION_ID" NUMBER, 
	"WEATHER_CONDITION_ID" NUMBER, 
	"LIGHTING_CONDITION_ID" NUMBER, 
	"ROADWAY_SURFACE_COND_ID" NUMBER, 
	"FIRST_CRASH_TYPE_ID" NUMBER, 
	"TRAFFICWAY_TYPE_ID" NUMBER, 
	"ALIGNMENT_ID" NUMBER, 
	"ROAD_DEFECT_ID" NUMBER, 
	"REPORT_TYPE_ID" NUMBER, 
	"CRASH_TYPE_ID" NUMBER, 
	"DAMAGE_ID" NUMBER, 
	"PRIM_CONTRIBUTORY_CAUSE_ID" NUMBER, 
	"SEC_CONTRIBUTORY_CAUSE_ID" NUMBER, 
	"STREET_DIRECTION_ID" NUMBER, 
	"STREET_NAME_ID" NUMBER, 
	"WORK_ZONE_TYPE_ID" NUMBER, 
	"MOST_SEVERE_INJURY_ID" NUMBER, 
	"LATITUDE" NUMBER, 
	"LONGITUDE" NUMBER, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "A01_TRAFFIC_CONTROL_DEVICE" 
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"TRAFFIC_CONTROL_DEVICE" VARCHAR2(50) NOT NULL ENABLE, 
	 CONSTRAINT "A01_TRAFFIC_CONTROL_DEVICE_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "A01_WEATHER_CONDITION" 
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"WEATHER_CONDITION" VARCHAR2(50) NOT NULL ENABLE, 
	 CONSTRAINT "A01_WEATHER_CONDITION_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "A01_WORK_ZONE_TYPE" 
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"WORK_ZONE_TYPE" VARCHAR2(50) NOT NULL ENABLE, 
	 CONSTRAINT "A01_WORK_ZONE_TYPE_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE UNIQUE INDEX "A01_ALIGNMENT_UQ1" ON "A01_ALIGNMENT" ("ALIGNMENT") 
  ;

  CREATE UNIQUE INDEX "A01_CONTRIBUTORY_CAUSE_UQ1" ON "A01_CONTRIBUTORY_CAUSE" ("CONTRIBUTORY_CAUSE") 
  ;

  CREATE UNIQUE INDEX "A01_CRASH_TYPE_UQ1" ON "A01_CRASH_TYPE" ("CRASH_TYPE") 
  ;

  CREATE UNIQUE INDEX "A01_DAMAGE_UQ1" ON "A01_DAMAGE" ("DAMAGE") 
  ;

  CREATE UNIQUE INDEX "A01_DEVICE_CONDITION_UQ1" ON "A01_DEVICE_CONDITION" ("DEVICE_CONDITION") 
  ;

  CREATE UNIQUE INDEX "A01_FIRST_CRASH_TYPE_UQ1" ON "A01_FIRST_CRASH_TYPE" ("FIRST_CRASH_TYPE") 
  ;

  CREATE UNIQUE INDEX "A01_LIGHTING_CONDITION_UQ1" ON "A01_LIGHTING_CONDITION" ("LIGHTING_CONDITION") 
  ;

  CREATE UNIQUE INDEX "A01_MOST_SEVERE_INJURY_UQ1" ON "A01_MOST_SEVERE_INJURY" ("MOST_SEVERE_INJURY") 
  ;

  CREATE UNIQUE INDEX "A01_REPORT_TYPE_UQ1" ON "A01_REPORT_TYPE" ("REPORT_TYPE") 
  ;

  CREATE UNIQUE INDEX "A01_ROAD_DEFECT_UQ1" ON "A01_ROAD_DEFECT" ("ROAD_DEFECT") 
  ;

  CREATE UNIQUE INDEX "A01_ROADWAY_SURFACE_COND_UQ1" ON "A01_ROADWAY_SURFACE_COND" ("ROADWAY_SURFACE_COND") 
  ;

  CREATE UNIQUE INDEX "A01_STREET_DIRECTION_UQ1" ON "A01_STREET_DIRECTION" ("STREET_DIRECTION") 
  ;

  CREATE UNIQUE INDEX "A01_STREET_NAME_UQ1" ON "A01_STREET_NAME" ("STREET_NAME") 
  ;

  ALTER TABLE "A01_TRAFFIC_ACCIDENTS" ADD CONSTRAINT "A01_TRAFFIC_ACCIDENTS_STREET_NAME_FK" FOREIGN KEY ("STREET_NAME_ID")
	  REFERENCES "A01_STREET_NAME" ("ID") ENABLE;
  ALTER TABLE "A01_TRAFFIC_ACCIDENTS" ADD CONSTRAINT "A01_TRAFFIC_ACCIDENTS_WORK_ZONE_TYPE_FK" FOREIGN KEY ("WORK_ZONE_TYPE_ID")
	  REFERENCES "A01_WORK_ZONE_TYPE" ("ID") ENABLE;
  ALTER TABLE "A01_TRAFFIC_ACCIDENTS" ADD CONSTRAINT "A01_TRAFFIC_ACCIDENTS_MOST_SEVERE_INJURY_FK" FOREIGN KEY ("MOST_SEVERE_INJURY_ID")
	  REFERENCES "A01_MOST_SEVERE_INJURY" ("ID") ENABLE;
  ALTER TABLE "A01_TRAFFIC_ACCIDENTS" ADD CONSTRAINT "A01_TRAFFIC_ACCIDENTS_ROAD_DEFECT_FK" FOREIGN KEY ("ROAD_DEFECT_ID")
	  REFERENCES "A01_ROAD_DEFECT" ("ID") ENABLE;
  ALTER TABLE "A01_TRAFFIC_ACCIDENTS" ADD CONSTRAINT "A01_TRAFFIC_ACCIDENTS_TRAFFIC_CONTROL_DEVICE_FK" FOREIGN KEY ("TRAFFIC_CONTROL_DEVICE_ID")
	  REFERENCES "A01_TRAFFIC_CONTROL_DEVICE" ("ID") ENABLE;
  ALTER TABLE "A01_TRAFFIC_ACCIDENTS" ADD CONSTRAINT "A01_TRAFFIC_ACCIDENTS_DEVICE_CONDITION_FK" FOREIGN KEY ("DEVICE_CONDITION_ID")
	  REFERENCES "A01_DEVICE_CONDITION" ("ID") ENABLE;
  ALTER TABLE "A01_TRAFFIC_ACCIDENTS" ADD CONSTRAINT "A01_TRAFFIC_ACCIDENTS_WEATHER_CONDITION_FK" FOREIGN KEY ("WEATHER_CONDITION_ID")
	  REFERENCES "A01_WEATHER_CONDITION" ("ID") ENABLE;
  ALTER TABLE "A01_TRAFFIC_ACCIDENTS" ADD CONSTRAINT "A01_TRAFFIC_ACCIDENTS_LIGHTING_CONDITION_FK" FOREIGN KEY ("LIGHTING_CONDITION_ID")
	  REFERENCES "A01_LIGHTING_CONDITION" ("ID") ENABLE;
  ALTER TABLE "A01_TRAFFIC_ACCIDENTS" ADD CONSTRAINT "A01_TRAFFIC_ACCIDENTS_ROADWAY_SURFACE_COND_FK" FOREIGN KEY ("ROADWAY_SURFACE_COND_ID")
	  REFERENCES "A01_ROADWAY_SURFACE_COND" ("ID") ENABLE;
  ALTER TABLE "A01_TRAFFIC_ACCIDENTS" ADD CONSTRAINT "A01_TRAFFIC_ACCIDENTS_FIRST_CRASH_TYPE_FK" FOREIGN KEY ("FIRST_CRASH_TYPE_ID")
	  REFERENCES "A01_FIRST_CRASH_TYPE" ("ID") ENABLE;
  ALTER TABLE "A01_TRAFFIC_ACCIDENTS" ADD CONSTRAINT "A01_TRAFFIC_ACCIDENTS_TRAFFICWAY_TYPE_FK" FOREIGN KEY ("TRAFFICWAY_TYPE_ID")
	  REFERENCES "A01_TRAFFICWAY_TYPE" ("ID") ENABLE;
  ALTER TABLE "A01_TRAFFIC_ACCIDENTS" ADD CONSTRAINT "A01_TRAFFIC_ACCIDENTS_ALIGNMENT_FK" FOREIGN KEY ("ALIGNMENT_ID")
	  REFERENCES "A01_ALIGNMENT" ("ID") ENABLE;
  ALTER TABLE "A01_TRAFFIC_ACCIDENTS" ADD CONSTRAINT "A01_TRAFFIC_ACCIDENTS_REPORT_TYPE_FK" FOREIGN KEY ("REPORT_TYPE_ID")
	  REFERENCES "A01_REPORT_TYPE" ("ID") ENABLE;
  ALTER TABLE "A01_TRAFFIC_ACCIDENTS" ADD CONSTRAINT "A01_TRAFFIC_ACCIDENTS_CRASH_TYPE_FK" FOREIGN KEY ("CRASH_TYPE_ID")
	  REFERENCES "A01_CRASH_TYPE" ("ID") ENABLE;
  ALTER TABLE "A01_TRAFFIC_ACCIDENTS" ADD CONSTRAINT "A01_TRAFFIC_ACCIDENTS_DAMAGE_FK" FOREIGN KEY ("DAMAGE_ID")
	  REFERENCES "A01_DAMAGE" ("ID") ENABLE;
  ALTER TABLE "A01_TRAFFIC_ACCIDENTS" ADD CONSTRAINT "A01_TRAFFIC_ACCIDENTS_PRIM_CONTRIBUTORY_CAUSE_FK" FOREIGN KEY ("PRIM_CONTRIBUTORY_CAUSE_ID")
	  REFERENCES "A01_CONTRIBUTORY_CAUSE" ("ID") ENABLE;
  ALTER TABLE "A01_TRAFFIC_ACCIDENTS" ADD CONSTRAINT "A01_TRAFFIC_ACCIDENTS_SEC_CONTRIBUTORY_CAUSE_FK" FOREIGN KEY ("SEC_CONTRIBUTORY_CAUSE_ID")
	  REFERENCES "A01_CONTRIBUTORY_CAUSE" ("ID") ENABLE;
  ALTER TABLE "A01_TRAFFIC_ACCIDENTS" ADD CONSTRAINT "A01_TRAFFIC_ACCIDENTS_STREET_DIRECTION_FK" FOREIGN KEY ("STREET_DIRECTION_ID")
	  REFERENCES "A01_STREET_DIRECTION" ("ID") ENABLE;

  CREATE UNIQUE INDEX "A01_TRAFFIC_CONTROL_DEVICE_UQ1" ON "A01_TRAFFIC_CONTROL_DEVICE" ("TRAFFIC_CONTROL_DEVICE") 
  ;

  CREATE UNIQUE INDEX "A01_TRAFFICWAY_TYPE_UQ1" ON "A01_TRAFFICWAY_TYPE" ("TRAFFICWAY_TYPE") 
  ;

  CREATE UNIQUE INDEX "A01_WEATHER_CONDITION_UQ1" ON "A01_WEATHER_CONDITION" ("WEATHER_CONDITION") 
  ;

  CREATE UNIQUE INDEX "A01_WORK_ZONE_TYPE_UQ1" ON "A01_WORK_ZONE_TYPE" ("WORK_ZONE_TYPE") 
  ;

  CREATE UNIQUE INDEX "A01_ALIGNMENT_PK" ON "A01_ALIGNMENT" ("ID") 
  ;

  CREATE UNIQUE INDEX "A01_ALIGNMENT_UQ1" ON "A01_ALIGNMENT" ("ALIGNMENT") 
  ;

  CREATE UNIQUE INDEX "A01_CONTRIBUTORY_CAUSE_PK" ON "A01_CONTRIBUTORY_CAUSE" ("ID") 
  ;

  CREATE UNIQUE INDEX "A01_CONTRIBUTORY_CAUSE_UQ1" ON "A01_CONTRIBUTORY_CAUSE" ("CONTRIBUTORY_CAUSE") 
  ;

  CREATE UNIQUE INDEX "A01_CRASH_TYPE_PK" ON "A01_CRASH_TYPE" ("ID") 
  ;

  CREATE UNIQUE INDEX "A01_CRASH_TYPE_UQ1" ON "A01_CRASH_TYPE" ("CRASH_TYPE") 
  ;

  CREATE UNIQUE INDEX "A01_DAMAGE_PK" ON "A01_DAMAGE" ("ID") 
  ;

  CREATE UNIQUE INDEX "A01_DAMAGE_UQ1" ON "A01_DAMAGE" ("DAMAGE") 
  ;

  CREATE UNIQUE INDEX "A01_DEVICE_CONDITION_PK" ON "A01_DEVICE_CONDITION" ("ID") 
  ;

  CREATE UNIQUE INDEX "A01_DEVICE_CONDITION_UQ1" ON "A01_DEVICE_CONDITION" ("DEVICE_CONDITION") 
  ;

  CREATE UNIQUE INDEX "A01_FIRST_CRASH_TYPE_PK" ON "A01_FIRST_CRASH_TYPE" ("ID") 
  ;

  CREATE UNIQUE INDEX "A01_FIRST_CRASH_TYPE_UQ1" ON "A01_FIRST_CRASH_TYPE" ("FIRST_CRASH_TYPE") 
  ;

  CREATE UNIQUE INDEX "A01_LIGHTING_CONDITION_PK" ON "A01_LIGHTING_CONDITION" ("ID") 
  ;

  CREATE UNIQUE INDEX "A01_LIGHTING_CONDITION_UQ1" ON "A01_LIGHTING_CONDITION" ("LIGHTING_CONDITION") 
  ;

  CREATE UNIQUE INDEX "A01_MOST_SEVERE_INJURY_PK" ON "A01_MOST_SEVERE_INJURY" ("ID") 
  ;

  CREATE UNIQUE INDEX "A01_MOST_SEVERE_INJURY_UQ1" ON "A01_MOST_SEVERE_INJURY" ("MOST_SEVERE_INJURY") 
  ;

  CREATE UNIQUE INDEX "A01_REPORT_TYPE_PK" ON "A01_REPORT_TYPE" ("ID") 
  ;

  CREATE UNIQUE INDEX "A01_REPORT_TYPE_UQ1" ON "A01_REPORT_TYPE" ("REPORT_TYPE") 
  ;

  CREATE UNIQUE INDEX "A01_ROADWAY_SURFACE_COND_PK" ON "A01_ROADWAY_SURFACE_COND" ("ID") 
  ;

  CREATE UNIQUE INDEX "A01_ROADWAY_SURFACE_COND_UQ1" ON "A01_ROADWAY_SURFACE_COND" ("ROADWAY_SURFACE_COND") 
  ;

  CREATE UNIQUE INDEX "A01_ROAD_DEFECT_PK" ON "A01_ROAD_DEFECT" ("ID") 
  ;

  CREATE UNIQUE INDEX "A01_ROAD_DEFECT_UQ1" ON "A01_ROAD_DEFECT" ("ROAD_DEFECT") 
  ;

  CREATE UNIQUE INDEX "A01_STREET_DIRECTION_PK" ON "A01_STREET_DIRECTION" ("ID") 
  ;

  CREATE UNIQUE INDEX "A01_STREET_DIRECTION_UQ1" ON "A01_STREET_DIRECTION" ("STREET_DIRECTION") 
  ;

  CREATE UNIQUE INDEX "A01_STREET_NAME_PK" ON "A01_STREET_NAME" ("ID") 
  ;

  CREATE UNIQUE INDEX "A01_STREET_NAME_UQ1" ON "A01_STREET_NAME" ("STREET_NAME") 
  ;

  CREATE UNIQUE INDEX "A01_TRAFFICWAY_TYPE_PK" ON "A01_TRAFFICWAY_TYPE" ("ID") 
  ;

  CREATE UNIQUE INDEX "A01_TRAFFICWAY_TYPE_UQ1" ON "A01_TRAFFICWAY_TYPE" ("TRAFFICWAY_TYPE") 
  ;

  CREATE UNIQUE INDEX "A01_TRAFFIC_CONTROL_DEVICE_PK" ON "A01_TRAFFIC_CONTROL_DEVICE" ("ID") 
  ;

  CREATE UNIQUE INDEX "A01_TRAFFIC_CONTROL_DEVICE_UQ1" ON "A01_TRAFFIC_CONTROL_DEVICE" ("TRAFFIC_CONTROL_DEVICE") 
  ;

  CREATE UNIQUE INDEX "A01_WEATHER_CONDITION_PK" ON "A01_WEATHER_CONDITION" ("ID") 
  ;

  CREATE UNIQUE INDEX "A01_WEATHER_CONDITION_UQ1" ON "A01_WEATHER_CONDITION" ("WEATHER_CONDITION") 
  ;

  CREATE UNIQUE INDEX "A01_WORK_ZONE_TYPE_PK" ON "A01_WORK_ZONE_TYPE" ("ID") 
  ;

  CREATE UNIQUE INDEX "A01_WORK_ZONE_TYPE_UQ1" ON "A01_WORK_ZONE_TYPE" ("WORK_ZONE_TYPE") 
  ;



  CREATE OR REPLACE FORCE EDITIONABLE VIEW "A01_TRAFFIC_ACCIDENTS_VW" ("ID", "CRASH_TYPE", "FIRST_CRASH_TYPE", "FIRST_CRASH_TYPE_GROUP", "CRASH_DATE_TIME", "CRASH_DATE", "CRASH_TIME", "CRASH_DAY", "CRASH_DAY_SHORT", "CRASH_MONTH", "CRASH_MONTH_SHORT", "CRASH_YEAR", "CRASH_DAY_LABEL", "CRASH_MONTH_LABEL", "CRASH_DAY_SHORT_LABEL", "CRASH_MONTH_SHORT_LABEL", "CRASH_DAY_NUM", "CRASH_MONTH_NUM", "CRASH_HOUR", "NUM_UNITS", "PRIMARY_CAUSE", "SECONDARY_CAUSE", "PRIMARY_CAUSE_GROUP", "SECONDARY_CAUSE_GROUP", "POSTED_SPEED_LIMIT", "SPEED_BUCKET", "STREET_DIRECTION", "STREET_NAME", "STREET_NO", "LATITUDE", "LONGITUDE", "TRAFFIC_CONTROL_DEVICE", "TRAFFIC_CONTROL_DEVICE_GROUP", "DEVICE_CONDITION", "DEVICE_CONDITION_GROUP", "WEATHER_CONDITION", "WEATHER_GROUP", "LIGHTING_CONDITION", "LIGHTING_GROUP", "ROADWAY_SURFACE_COND", "ROADWAY_SURFACE_GROUP", "NUM_ROAD_LANES", "LANE_BUCKET", "ALIGNMENT", "ALIGNMENT_GROUP", "TRAFFICWAY_TYPE", "TRAFFICWAY_TYPE_GROUP", "ROAD_DEFECT", "ROAD_DEFECT_GROUP", "ROAD_DEFECT_BINARY", "DAMAGE", "DATE_POLICE_NOTIFIED", "REPORT_TYPE", "REPORT_TYPE_GROUP", "BEAT_OF_OCCURRENCE", "WORK_ZONE_TYPE", "HIT_AND_RUN", "HIT_AND_RUN_GROUP", "DOORING", "WORK_ZONE", "WORKERS_PRESENT", "WORKERS_PRESENT_GROUP", "MOST_SEVERE_INJURY", "MOST_SEVERE_INJURY_GROUP", "INJURIES_TOTAL", "INJURIES_FATAL", "INJURIES_INCAPACITATING", "INJURIES_NON_INCAPACITATING", "INJURIES_REPORTED_NOT_EVIDENT", "INJURIES_NO_INDICATION", "INJURIES_UNKNOWN") AS 
  select ta.id, 
          --ta.crash_record_id, 
          --ta.crash_date_est_i as crash_date_est, 
          --ta.crash_type_id, 
          ct.crash_type,       
 
          --ta.first_crash_type_id,________________________________________________________ 
          fct.first_crash_type,   
          case 
             when fct.first_crash_type in ('REAR END','REAR TO FRONT') then 'REAR-END' 
             when fct.first_crash_type in ('SIDESWIPE SAME DIRECTION','SIDESWIPE OPPOSITE DIRECTION') then 'SIDESWIPE' 
             when fct.first_crash_type in ('TURNING') then 'TURNING' 
             when fct.first_crash_type in ('ANGLE','REAR TO SIDE') then 'ANGLE' 
             when fct.first_crash_type in ('HEAD ON') then 'HEAD-ON' 
             when fct.first_crash_type in ('PARKED MOTOR VEHICLE') then 'PARKED VEHICLE' 
             when fct.first_crash_type in ('FIXED OBJECT','OTHER OBJECT') then 'OBJECT' 
             when fct.first_crash_type in ('PEDESTRIAN') then 'PEDESTRIAN' 
             when fct.first_crash_type in ('PEDALCYCLIST') then 'PEDALCYCLIST' 
             when fct.first_crash_type in ('REAR TO REAR','OTHER NONCOLLISION','OVERTURNED','ANIMAL','TRAIN') then 'OTHER' 
          end as first_crash_type_group, 
 
          -- DATE TIME FIELDS _____________________________________________________________________________ 
 
          to_char(ta.crash_date, 'DD/MM/YYYY HH24:MI:SS') as crash_date_time, -- 22/09/2023 06:40:00 
          trunc(ta.crash_date) as crash_date, -- 22/09/2023 
 
          -- TO CHAR per estrazione di certi dati da mostrare nei grafici    
          to_char(ta.crash_date, 'HH24:MI') as crash_time, -- 06:40 (già ordinabile) 
          trim(to_char(ta.crash_date, 'DAY', 'NLS_DATE_LANGUAGE=ENGLISH')) as crash_day, -- FRIDAY (trim per gli spazi alla fine) 
          to_char(ta.crash_date, 'DY', 'NLS_DATE_LANGUAGE=ENGLISH') as crash_day_short, -- FRI 
          trim(to_char(ta.crash_date, 'MONTH', 'NLS_DATE_LANGUAGE=ENGLISH')) as crash_month, -- SEPTEMBER 
          to_char(ta.crash_date, 'MON', 'NLS_DATE_LANGUAGE=ENGLISH') as crash_month_short, -- SEP 
          to_char(ta.crash_date, 'YYYY') as crash_year, -- 2023 (già ordinabile) 
 
          -- LABEL per i malfunzionamenti nell'ordinamento sui grafici a più serie 
          to_char(ta.crash_date, 'D') || ' - ' || trim(to_char(ta.crash_date, 'DAY', 'NLS_DATE_LANGUAGE=ENGLISH')) as crash_day_label, -- 5 - FRIDAY 
          to_char(ta.crash_date, 'MM') || ' - ' || trim(to_char(crash_date, 'MONTH', 'NLS_DATE_LANGUAGE=ENGLISH')) as crash_month_label, -- 09 - SEPTEMBER 
          -- Label giorno (prefisso numerico + abbreviazione) 
          lpad(to_char(ta.crash_date, 'D'), 2, '0') || ' - ' || to_char(ta.crash_date, 'DY', 'NLS_DATE_LANGUAGE=ENGLISH') as crash_day_short_label, -- 05 - FRI 
          -- Label mese (prefisso numerico a 2 cifre + abbreviazione) 
          to_char(ta.crash_date, 'MM') || ' - ' || to_char(ta.crash_date, 'MON', 'NLS_DATE_LANGUAGE=ENGLISH') as crash_month_short_label, -- 09 - SEP 
 
          -- FORMATI NUMERICI per ordinamento 
          to_char(ta.crash_date, 'D') as crash_day_num, -- 5 
          to_char(ta.crash_date, 'MM') as crash_month_num, -- 09 
          -- Orario arrotondato 
          to_char(round(ta.crash_date, 'HH'), 'HH24') || ':00' as crash_hour, -- 07:00 
 
          --_______________________________________________________________________________________________ 
 
          ta.num_units, 
 
          --ta.prim_contributory_cause_id, 
          pc.contributory_cause as primary_cause, 
          --ta.sec_contributory_cause_id 
          sc.contributory_cause as secondary_cause,  
          pc.cause_group as primary_cause_group, 
          sc.cause_group as secondary_cause_group, 
 
          -- SPEED + BUCKET __________________________________________      
          ta.posted_speed_limit,     
          case 
           when posted_speed_limit between 0 and 10 then '00-10' 
           when posted_speed_limit between 11 and 20 then '11-20' 
           when posted_speed_limit between 21 and 30 then '21-30' 
           when posted_speed_limit between 31 and 40 then '31-40' 
           when posted_speed_limit between 41 and 50 then '41-50' 
           else '51+' 
          end as speed_bucket, 
          --__________________________________________________________ 
 
          --ta.street_direction_id, 
          sd.street_direction_desc as street_direction,       
          --ta.street_name_id, 
          sn.street_name,       
          ta.street_no,       
          ta.latitude, 
          ta.longitude, 
 
          --ta.traffic_control_device_id,______________________________ 
          tcd.traffic_control_device,      
          case 
             when tcd.traffic_control_device in ('NO CONTROLS') then 'NO CONTROL' 
             when tcd.traffic_control_device in ('TRAFFIC SIGNAL','FLASHING CONTROL SIGNAL') then 'TRAFFIC SIGNALS' 
             when tcd.traffic_control_device in ('STOP SIGN/FLASHER','YIELD') then 'STOP/YIELD' 
             when tcd.traffic_control_device in ('LANE USE MARKING','NO PASSING','OTHER REG. SIGN') then 'REGULATORY/MARKINGS' 
             when tcd.traffic_control_device in ('PEDESTRIAN CROSSING SIGN','SCHOOL ZONE') then 'PEDESTRIAN/SCHOOL' 
             when tcd.traffic_control_device in ('RAILROAD CROSSING GATE','RR CROSSING SIGN','OTHER RAILROAD CROSSING') then 'RAILROAD' 
             when tcd.traffic_control_device in ('POLICE/FLAGMAN') then 'POLICE/FLAGMAN' 
             when tcd.traffic_control_device in ('UNKNOWN') then 'UNKNOWN' 
             else 'OTHER' 
          end as traffic_control_device_group, 
 
          --ta.device_condition_id,____________________________________ 
          dc.device_condition,     
          case 
             when dc.device_condition in ('NO CONTROLS') then 'NO CONTROL' 
             when dc.device_condition in ('FUNCTIONING PROPERLY') then 'FUNCTIONING' 
             when dc.device_condition in ('FUNCTIONING IMPROPERLY','NOT FUNCTIONING','MISSING','WORN REFLECTIVE MATERIAL') then 'NOT FUNCTIONING' 
             when dc.device_condition in ('UNKNOWN') then 'UNKNOWN' 
             else 'OTHER' 
          end as device_condition_group, 
 
          --ta.weather_condition_id, ____________________________________ 
          wc.weather_condition, 
          case 
             when wc.weather_condition in ('CLEAR') then 'CLEAR'          
             when wc.weather_condition in ('RAIN','FREEZING RAIN/DRIZZLE') then 'RAIN' 
             when wc.weather_condition in ('SNOW','BLOWING SNOW', 'SLEET/HAIL') then 'SNOW/HAIL'          
             when wc.weather_condition in ('CLOUDY/OVERCAST') then 'CLOUDY' 
             when wc.weather_condition in ('FOG/SMOKE/HAZE') then 'FOG' 
             when wc.weather_condition in ('SEVERE CROSS WIND GATE') then 'WIND' 
             when wc.weather_condition is null or wc.weather_condition in ('BLOWING SAND, SOIL, DIRT','UNKNOWN','OTHER') then 'UNKNOWN/OTHER' 
          end as weather_group,    
 
          --ta.lighting_condition_id, ___________________________________ 
          lc.lighting_condition,    
          case 
             when lc.lighting_condition in ('DAYLIGHT') then 'DAYLIGHT' 
             when lc.lighting_condition in ('DARKNESS','DARKNESS, LIGHTED ROAD') then 'DARKNESS' 
             when lc.lighting_condition in ('DAWN','DUSK') then 'DAWN/DUSK' 
             when lc.lighting_condition is null or lc.lighting_condition in ('UNKNOWN') then 'UNKNOWN/OTHER' 
          end as lighting_group, 
 
          --ta.roadway_surface_cond_id,__________________________________ 
          rsc.roadway_surface_cond,  
          case 
             when rsc.roadway_surface_cond in ('DRY') then 'DRY' 
             when rsc.roadway_surface_cond in ('WET') then 'WET' 
             when rsc.roadway_surface_cond in ('SNOW OR SLUSH') then 'SNOW/SLUSH' 
             when rsc.roadway_surface_cond in ('ICE') then 'ICE' 
             when rsc.roadway_surface_cond in ('SAND, MUD, DIRT') then 'SAND/MUD' 
             when rsc.roadway_surface_cond in ('UNKNOWN') then 'UNKNOWN' 
             else 'OTHER' 
          end as roadway_surface_group, 
 
          -- LANES ______________________________________________________ 
           
          ta.lane_cnt as num_road_lanes, 
          case 
             when ta.lane_cnt = 1 then '1' 
             when ta.lane_cnt = 2 then '2' 
             when ta.lane_cnt in (3,4) then '3–4' 
             when ta.lane_cnt >= 5 and ta.lane_cnt <= 12 then '5+' 
             else 'UNKNOWN/INVALID' 
          end as lane_bucket, 
          --______________________________________________________________ 
 
          --ta.alignment_id,______________________________________________          
          a.alignment,      
          case 
             when a.alignment in ('STRAIGHT AND LEVEL','STRAIGHT ON GRADE','STRAIGHT ON HILLCREST') then 'STRAIGHT' 
             when a.alignment in ('CURVE, LEVEL','CURVE ON GRADE','CURVE ON HILLCREST') then 'CURVE' 
          end as alignment_group, 
 
          --ta.trafficway_type_id,________________________________________ 
          tt.trafficway_type,  
          case 
             when tt.trafficway_type in ('NOT DIVIDED') then 'NOT DIVIDED' 
             when tt.trafficway_type like 'DIVIDED%' then 'DIVIDED' 
             when tt.trafficway_type in ('ONE-WAY') then 'ONE-WAY' 
             when tt.trafficway_type in ('FOUR WAY','T-INTERSECTION','Y-INTERSECTION','L-INTERSECTION','FIVE POINT, OR MORE','ROUNDABOUT') then 'INTERSECTION' 
             when tt.trafficway_type in ('PARKING LOT','DRIVEWAY','RAMP') then 'NON-ROADWAY' 
             when tt.trafficway_type in ('UNKNOWN','UNKNOWN INTERSECTION TYPE','NOT REPORTED','OTHER') then 'UNKNOWN/OTHER'              
             when tt.trafficway_type in ('ALLEY','CENTER TURN LANE','TRAFFIC ROUTE') then 'MINOR ROADS' 
          end as trafficway_type_group, 
 
           --ta.road_defect_id,____________________________________________ 
          rd.road_defect,    
          case 
             when rd.road_defect in ('NO DEFECTS') then 'NO DEFECTS' 
             when rd.road_defect in ('RUT, HOLES','WORN SURFACE') then 'SURFACE DAMAGE' 
             when rd.road_defect in ('SHOULDER DEFECT') then 'SHOULDER DEFECT' 
             when rd.road_defect in ('DEBRIS ON ROADWAY') then 'DEBRIS' 
             when rd.road_defect is null or rd.road_defect in ('UNKNOWN','OTHER') then 'UNKNOWN/OTHER' 
          end as road_defect_group, 
          case 
             when rd.road_defect in ('NO DEFECTS') then 'NO DEFECTS' 
             when rd.road_defect is null or rd.road_defect in ('UNKNOWN','OTHER') then 'UNKNOWN/OTHER' 
             else 'DEFECTED ROAD' 
          end as road_defect_binary, 
          --______________________________________________________________ 
 
          --ta.damage_id, 
          d.damage,       
          ta.date_police_notified, 
 
          --ta.report_type_id, ____________________________________________ 
          rt.report_type,  
          case  
             when report_type = 'ON SCENE' then 'ON-SITE REPORT' 
             when report_type = 'NOT ON SCENE (DESK REPORT)' then 'DESK REPORT' 
             when report_type = 'AMENDED' then 'AMENDED' 
             else 'UNKNOWN' 
          end as report_type_group, 
          --_______________________________________________________________ 
 
          ta.beat_of_occurrence, 
          --ta.work_zone_type_id, 
          wzt.work_zone_type,    
 
          -- Y/N indexes_________________________________________________ 
 
          --ta.intersection_related_i as intersection_related, 
          --ta.not_right_of_way_i as not_right_of_way,    
          --ta.photos_taken_i as photos_taken, 
          --ta.statements_taken_i as statements_taken, 
          ta.hit_and_run_i as hit_and_run, 
          case  
            when hit_and_run_i = 'N' then 'NON HIT & RUN' 
            when hit_and_run_i = 'Y' then 'HIT & RUN' 
            else 'NOT REPORTED' 
          end as hit_and_run_group, 
 
          ta.dooring_i as dooring, 
          ta.work_zone_i as work_zone, 
          ta.workers_present_i as workers_present, 
          case  
            when workers_present_i = 'N' then 'NO WORKERS' 
            when workers_present_i = 'Y' then 'WORKERS PRESENT' 
            else 'NOT REPORTED' 
          end as workers_present_group, 
 
          --ta.most_severe_injury_id,_____________________________________ 
          msi.most_severe_injury,  
          case 
             when msi.most_severe_injury in ('NO INDICATION OF INJURY') then 'NO INJURY' 
             when msi.most_severe_injury in ('NONINCAPACITATING INJURY','REPORTED, NOT EVIDENT') then 'MINOR INJURY' 
             when msi.most_severe_injury in ('INCAPACITATING INJURY') then 'SEVERE INJURY' 
             when msi.most_severe_injury in ('FATAL') then 'FATAL' 
             when msi.most_severe_injury is null then 'UNKNOWN' 
          end as most_severe_injury_group, 
          --______________________________________________________________ 
 
          ta.injuries_total, 
          ta.injuries_fatal, 
          ta.injuries_incapacitating, 
          ta.injuries_non_incapacitating, 
          ta.injuries_reported_not_evident, 
          ta.injuries_no_indication, 
          ta.injuries_unknown 
 
     from a01_traffic_accidents ta 
 
left join a01_contributory_cause      pc on ta.prim_contributory_cause_id =  pc.id 
left join a01_contributory_cause      sc on ta.sec_contributory_cause_id  =  sc.id 
left join a01_traffic_control_device tcd on ta.traffic_control_device_id  = tcd.id 
left join a01_device_condition        dc on ta.device_condition_id        =  dc.id 
left join a01_weather_condition       wc on ta.weather_condition_id       =  wc.id 
left join a01_lighting_condition      lc on ta.lighting_condition_id      =  lc.id 
left join a01_roadway_surface_cond   rsc on ta.roadway_surface_cond_id    = rsc.id 
left join a01_trafficway_type         tt on ta.trafficway_type_id         =  tt.id 
left join a01_alignment                a on ta.alignment_id               =   a.id 
left join a01_road_defect             rd on ta.road_defect_id             =  rd.id 
left join a01_first_crash_type       fct on ta.first_crash_type_id        = fct.id 
left join a01_report_type             rt on ta.report_type_id             =  rt.id 
left join a01_crash_type              ct on ta.crash_type_id              =  ct.id 
left join a01_damage                   d on ta.damage_id                  =   d.id 
left join a01_street_direction        sd on ta.street_direction_id        =  sd.id 
left join a01_street_name             sn on ta.street_name_id             =  sn.id 
left join a01_work_zone_type         wzt on ta.work_zone_type_id          = wzt.id 
left join a01_most_severe_injury     msi on ta.most_severe_injury_id      = msi.id;

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "A01_YEARS_VW" ("YEAR_DISPLAY", "YEAR_RETURN") AS 
  select 2014 + level year_display,
       2014 + level year_return
  from dual 
connect by level + 2014 < 2024;